#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/5/12
 * Time: 09:46
 */


require(__DIR__.'/Tuzhi.php');


Tuzhi::init(
    [
        'class'=>'tuzhi\base\Configure'
    ]
);

Tuzhi::make(
    [
        'class'=>'tuzhi\console\Application',

        'charset' => 'utf-8',

        'timezone' => 'PRC' ,
    ]
);

Tuzhi::App()->run();