<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 2016/12/1
 * Time: 00:04
 */

namespace tuzhi\support\profiler;

use tuzhi\base\Application;
use tuzhi\base\Event;
use tuzhi\base\Object;
use tuzhi\helper\Arr;
use tuzhi\helper\Html;
use tuzhi\web\Response;

/**
 *  分析
 *
 * 1. 布置锚点 监听事件
 * 2. 促发事件 采集事件
 * 3. 存储数据
 * 4. 显示数据
 *
 * Class Profiles
 * @package tuzhi\support\profiles
 */
class Profiler extends Object
{
    /**
     * @var array
     */
    protected $componentsMaps =
        [
            'app'=>'tuzhi\support\profiler\collect\AppCollect',
            'sql'=>'tuzhi\support\profiler\collect\DbCollect'
        ];

    /**
     * @var array
     */
    protected $components = [];

    /**
     * @var array
     */
    protected $collectData =[];

    /**
     *
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        foreach ($this->componentsMaps as $name=>$class){
            $this->components[$name] = new $class();
        }
    }

    /**
     *
     */
    public function eventRegister()
    {
        Arr::each($this->components,function( $key,$value ){
            call_user_func([$value,'register']);
        });
        // 注册结束事件
        Event::on(
            Application::className(),
            Application::EVENT_APP_END,
            [$this,'eventAppEnd']
        );
    }

    /**
     *
     */
    public function eventAppEnd()
    {
        //收集数据
        $collectData =[];
        Arr::each($this->components,function ($key,$value) use( & $collectData ){
            $collectData = array_merge($collectData,call_user_func([$value,'collect']));
        });
        $this->collectData = $collectData;
        //处理显示？

        //TODO:: 显示逻辑处理掉//
        if( ! \Request::isAjax()
            //&& ! \Request::isPajax()
            && \tuzhi\web\Application::Response()->content instanceof \tuzhi\web\response\Html
        ){
            $this->console();
        }

    }

    public function console()
    {
        $console = [];
        $console[] =$this->consoleLog('============================ TUZHI PROFILER CONSOLE ===================================');
        foreach ($this->collectData as $name=>$data){
            $console[] = $this->consoleLog('---------- '.$name.' ----------');
            foreach ($data as $k=>$v){
                if(is_array($v)){
                    foreach($v as $time=>$value){
                        $console[] = $this->consoleLog($time.' ==> '.join(' || ',$value));
                    }
                }else{
                    $console[] = $this->consoleLog($k.' ==> '.$v);
                }
            }
        }
        echo Html::script(null,"\n".join("\n",$console));
    }

    protected function consoleLog( $message )
    {
        return 'console.log("'.$message.'");';
    }

}