<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/8/30
 * Time: 22:03
 */

namespace tuzhi\console;

use tuzhi\base\Object;
use tuzhi\contracts\web\IRequest;

class Request extends Object implements IRequest
{

    /**
     * @var
     */
    protected $params;

    protected $route ='';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->getParams();
    }

    public function getParams()
    {
        if( $this->params == null ) {
            if( isset($_SERVER['argv']) ){
                $this->params = $_SERVER['argv'];
                //
                array_shift($this->params);
            }else{
                $this->params = [];
            }
        }
        //
        $this->route = array_shift($this->params);
        return $this->params;
    }

    /**
     * @return mixed
     */
    public function getRoute()
    {
        return $this->route;
    }

    /**
     * 意义?
     */
    public function all()
    {
        // TODO: Implement all() method.
    }
}