#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/5/12
 * Time: 09:46
 */

/**
 * 项目APP 目录
 */
define('APP_PATH', __DIR__ );

/**
 * 引入框架
 */
require __DIR__.'/../framework/tuzhi/Tuzhi.php';


/**
 * 初始化配置
 */
Tuzhi::init(
    (require __DIR__.'/config/consoleConfig.php')
);

/**
 *
 */
Tuzhi::App()->run();