<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/4/5
 * Time: 11:15
 */

namespace tuzhi\log;


use tuzhi\base\Server;

/**
 * Class Log
 * @package tuzhi\log
 */
class Log extends Server
{
    const LOG_NOTICE  = 1;

    const LOG_WARNING = 2;

    const LOG_ERROR   = 4;

    const LOG_ALL     = 7;


    /**
     * @var int
     */
    protected $allow = 4;

    protected static $logs = [];

    private $storage = null;


    public function __configure(  array $config = [])
    {

        parent::__configure($config); // TODO: Change the autogenerated stub
    }

    /**
     * 启动 OR 初始化
     */
    public function start()
    {
        $this->storage = \Tuzhi::make($this->storage);
        parent::start();
    }

    public  function notice( $message )
    {
        if( Log::LOG_NOTICE & $this->allow )
        {
            static::$logs[ Log::LOG_NOTICE ] = $message;
        }
    }

    public  function warning( $message )
    {

    }

    public  function error( $message )
    {

    }

    public function stop () {
        //清空数据
        parent::stop();
    }
}