<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/4/5
 * Time: 11:15
 */

namespace tuzhi\log;


use tuzhi\base\Serve;
use tuzhi\contracts\log\IStorage;

/**
 * Class Log
 * @package tuzhi\log
 */
class Log extends Serve
{
    const LOG_NOTICE  = 1;

    const LOG_WARNING = 2;

    const LOG_ERROR   = 4;

    const LOG_ALL     = 7;


    /**
     * @var int
     */
    protected $allow = 4;

    protected static $logs = [];

    private $storage = null;


    public function __configure( IStorage $storage , array $config = [])
    {
        $this->storage = $storage;
        parent::__configure($config); // TODO: Change the autogenerated stub
    }

    public  function notice( $message )
    {
        if( Log::LOG_NOTICE & $this->allow )
        {
            static::$logs[] = $message;
        }
    }

    public  function warning( $message )
    {

    }

    public  function error( $message )
    {

    }
}