<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/4/2
 * Time: 15:18
 */

namespace tuzhi\base;

/**
 * 配置文件  注意  @分类
 *
 * Class Configure
 * @package tuzhi\base
 */
class Configure extends Serve{

    public $serveName = 'config';

    protected static $config;

    protected $separator = '.';


    public function __configure(array $config = [])
    {
        parent::__configure($config); // TODO: Change the autogenerated stub
    }

    /**
     * 简单粗暴
     * @param $file
     * @return bool
     * @see   set()
     */
    public  function loadFileConfig( $file )
    {
        if( file_exists( $file ) ){
            $config = include $file;
            static::$config = array_merge(static::$config ,$config);
            return true;
        }
        return false;
    }

    /**
     *
     * @param $key
     * @return null
     */
    public  function get($key)
    {
        // 获取别名操作
        if( substr($key,0,1) == '@' ){
            //查找 并替换
            $searchKey = substr($key,1);
            // 是否缓存结果?
        }
        $searchKey = $key;
        $searchArr = @explode('.',$searchKey);

        $result = static::$config;

        while( count( $searchArr ) ){

            $k = array_shift( $searchArr );

            if( isset( $result[$k] ) ){
                $result = $result[$k];
            }else{
                $result = null;
                break;
            }
        }

        return $result;
    }

    /**
     * @param $key
     * @param null $value
     * @return $this
     */
    public  function set($key,$value = null)
    {
        $searchArr = @explode('.',$key);

        $result = &static::$config;

        while( count( $searchArr ) ){

            $k = array_shift( $searchArr );

            if( isset( $result[$k] ) ){
                $result = $result[$k];
            }else{
                $result[$k] = [];
            }
        }

        if( is_array( $result ) ){
            $result = is_array($value) ?  array_merge( $result,$value ) : $value;
        }else{
            $result = $value;
        }
        return $this;
    }

    public function all()
    {
        return static::$config;
    }

    /**
     * 从缓存中读取
     */
    public function load()
    {

    }

    /**
     * 把配置写入缓存
     */
    public function save()
    {

    }

}