<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/4/5
 * Time: 10:29
 */

namespace tuzhi\base;


/**
 * APP 对应的服务
 * 
 * Class Serve
 * @package tuzhi\base
 */
class Serve extends Object
{
    const STATUS_RUNNING = 1;

    const STATUS_STOP = 0;

    public $serveName;

    protected $isRegister = false;

    protected $status;


    public function __configure(array $config = [])
    {
        parent::__configure($config); // TODO: Change the autogenerated stub
    }

    /**
     * 注册入 app   是否强制  force
     */
    public function registered( Application $app )
    {
        $app->register( $this );
        $this->isRegister = true;
    }

    /**
     * 启动
     */
    public function start()
    {
        $this->status = Serve::STATUS_RUNNING;
    }

    /**
     * 停止
     */
    public function stop()
    {
        $this->status = Serve::STATUS_STOP;
    }


    public function getServeName()
    {
        return $this->serveName;
    }

}