<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 2016/12/1
 * Time: 00:06
 */

namespace tuzhi\support\profiler\collect;

use tuzhi\contracts\base\IEvent;
use tuzhi\support\profiler\Counter;
use tuzhi\support\profiler\Collection;
use tuzhi\base\Event;
use tuzhi\web\Application;
use tuzhi\support\profiler\Timer;
use tuzhi\support\profiler\Memory;

/**
 * Class ProgramProfiles
 * @package tuzhi\support\profiles
 */
class AppCollect extends Collection
{
    /**
     *
     */
    const EVENT_PROFILER_APP_COLLECT='event.profiler.app.collect';

    /**
     * @return mixed
     */
    public function register()
    {
        Event::on(
            Application::className(),
            Application::EVENT_BEFORE_RUN,
            function(){
                Timer::mark('tuzhi.run.start');
            }
        );

        Event::on(
            Application::className(),
            Application::EVENT_AFTER_RUN,
            function (){
                Timer::mark('tuzhi.run.end');
        });

        Event::on(
            Application::className(),
            Application::EVENT_APP_END,
            function (){
                Timer::mark('tuzhi.end');
                Memory::mark('tuzhi.end');
        });

    }

    /**
     * @return array
     */
    public function collect()
    {
        $this['app.totalTime']            = Timer::slice('tuzhi');
        $this['app.runTime']              = Timer::slice('tuzhi.run');
        $this['app.totalMemory']          = Memory::slice('tuzhi');
        $this['app.view.renderFileTime']  = Timer::slice('tuzhi.view.renderFile');
        $this['app.view.renderFileCount'] = Counter::last('tuzhi.view.renderFile');
        $this['app.db.connectionTime']    = Timer::slice('tuzhi.db.connection');
        $this['app.db.connection.rate']   = number_format( ($this['app.db.connectionTime']/ $this['app.totalTime'])*100 ,2).'%';
        $this['app.db.connectionCount']   = Counter::last('tuzhi.db.connection');


        Event::trigger(
            $this,
            AppCollect::EVENT_PROFILER_APP_COLLECT,
            $this
        );

        return parent::collect(); // TODO: Change the autogenerated stub
    }
}