<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 2016/12/1
 * Time: 15:46
 */

namespace tuzhi\support\profiler\collect;


use tuzhi\base\Event;
use tuzhi\contracts\base\IEvent;
use tuzhi\db\Command;
use tuzhi\support\profiler\Collection;

/**
 * Class Sql
 * @package tuzhi\support\profiler\components
 */
class DbCollect extends Collection
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this['execute'] = [];
        $this['query'] = [];
    }

    /**
     *
     */
    public function register()
    {
        Event::on(
            Command::className(),
            Command::EVENT_AFTER_EXECUTE,
            [$this,'afterExecute']);

        Event::on(
            Command::className(),
            Command::EVENT_AFTER_QUERY,
            [$this,'afterQuery']
        );
    }

    /**
     * @param $data
     */
    public function afterExecute( $data )
    {
        $this->data['execute'][] = $data;
    }

    /**
     * @param $data
     */
    public function afterQuery( $data)
    {
        $this->data['query'][]  = $data;
    }


}