<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 16/4/9
 * Time: 14:39
 */

namespace tuzhi\web;


class ErrorHandler extends \tuzhi\base\ErrorHandler {


    protected $view = '&tuzhi/resource/view/error/error.php';


    public function __configure(array $config = [])
    {
        parent::__configure($config); // TODO: Change the autogenerated stub
    }



    protected function renderException( $exception )
    {

    }


}