<?php
/**
 * Created by PhpStorm.
 * User: 吾色禅师<wuse@chanshi.me>
 * Date: 2016/11/1
 * Time: 10:45
 */

namespace tuzhi\support\files;


use tuzhi\model\ArrayData;
use tuzhi\model\Model;

/**
 * Class FilesCollect
 * @package tuzhi\support\files
 */
class FilesCollect extends ArrayData
{
    /**
     * @var array
     */
    //protected $collection = [];


    /**
     * @return mixed
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initCollection();
    }

    /**
     * @return bool
     */
    protected function initCollection()
    {
        foreach ($_FILES as $name=>$file)
        {
            if( is_array( $_FILES[$name]['name']) ){
                $collect =[];
                foreach ($_FILES[$name]['name'] as $i=>$value){
                    $collect[$i] = new Files([
                        'file'=>$value
                    ]);
                }
                $this->data[$name] = $collect;
            }else{
                $this->data[$name] = new Files([
                    'file'=> $file
                ]);
            }
        }
        return true;
    }
}